import { Document, Page, StyleSheet, Text, View } from '@react-pdf/renderer';
import type { FeeInvoice } from '@/types/models';
import { formatDate, formatMoney } from '@/lib/utils';

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, color: '#0F1C3F', fontFamily: 'Helvetica' },
  header: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 24, borderBottom: '2 solid #00C2CB', paddingBottom: 12 },
  brand: { fontSize: 22, fontWeight: 'bold', color: '#0F1C3F' },
  badge: { fontSize: 10, color: '#00A0A8' },
  title: { fontSize: 16, fontWeight: 'bold', marginBottom: 4 },
  row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  label: { color: '#475474' },
  section: { marginTop: 16 },
  tableHead: { flexDirection: 'row', backgroundColor: '#F3F4F7', padding: 8, marginTop: 8 },
  tableRow: { flexDirection: 'row', padding: 8, borderBottom: '1 solid #E2E5EC' },
  col1: { flex: 3 },
  col2: { flex: 1, textAlign: 'right' },
  totals: { marginTop: 16, alignSelf: 'flex-end', width: '50%' },
  totalRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 3 },
  grand: { flexDirection: 'row', justifyContent: 'space-between', borderTop: '1 solid #0F1C3F', marginTop: 6, paddingTop: 6, fontWeight: 'bold' },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, textAlign: 'center', color: '#78849E', fontSize: 9 },
});

export function InvoicePDF({ invoice, schoolName }: { invoice: FeeInvoice; schoolName: string }) {
  const amount = Number(invoice.amount);
  const paid = Number(invoice.amountPaid);
  const balance = invoice.balance ?? Math.max(0, amount - paid);
  const student = invoice.student;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.brand}>{schoolName}</Text>
            <Text style={styles.badge}>Powered by FenDux SMS</Text>
          </View>
          <View>
            <Text style={styles.title}>INVOICE</Text>
            <Text style={styles.label}>{invoice.invoiceNumber}</Text>
          </View>
        </View>

        <View style={styles.row}>
          <View>
            <Text style={styles.label}>Billed to</Text>
            <Text>{student ? `${student.firstName} ${student.lastName}` : 'Student'}</Text>
            {student && <Text style={styles.label}>{student.studentNumber}</Text>}
          </View>
          <View>
            <Text style={styles.label}>Due date</Text>
            <Text>{formatDate(invoice.dueDate)}</Text>
            <Text style={styles.label}>Status: {invoice.status}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <View style={styles.tableHead}>
            <Text style={styles.col1}>Description</Text>
            <Text style={styles.col2}>Amount</Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={styles.col1}>{invoice.feeStructure?.name ?? 'School fee'}</Text>
            <Text style={styles.col2}>{formatMoney(amount)}</Text>
          </View>
        </View>

        <View style={styles.totals}>
          <View style={styles.totalRow}>
            <Text style={styles.label}>Subtotal</Text>
            <Text>{formatMoney(amount)}</Text>
          </View>
          <View style={styles.totalRow}>
            <Text style={styles.label}>Paid</Text>
            <Text>{formatMoney(paid)}</Text>
          </View>
          <View style={styles.grand}>
            <Text>Balance due</Text>
            <Text>{formatMoney(balance)}</Text>
          </View>
        </View>

        <Text style={styles.footer}>
          This invoice was generated by FenDux SMS on {formatDate(new Date().toISOString())}.
        </Text>
      </Page>
    </Document>
  );
}
