import { Document, Page, StyleSheet, Text, View } from '@react-pdf/renderer';
import type { ReportCard } from '@/types/models';
import { formatDate } from '@/lib/utils';

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, color: '#0F1C3F', fontFamily: 'Helvetica' },
  header: { borderBottom: '2 solid #00C2CB', paddingBottom: 12, marginBottom: 20 },
  school: { fontSize: 20, fontWeight: 'bold' },
  sub: { fontSize: 10, color: '#00A0A8' },
  title: { fontSize: 14, fontWeight: 'bold', marginTop: 14 },
  meta: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8, marginBottom: 8 },
  label: { color: '#475474' },
  tableHead: { flexDirection: 'row', backgroundColor: '#0F1C3F', padding: 8, color: '#FFFFFF', marginTop: 10 },
  tableRow: { flexDirection: 'row', padding: 8, borderBottom: '1 solid #E2E5EC' },
  c1: { flex: 3 },
  c2: { flex: 1, textAlign: 'center' },
  c3: { flex: 1, textAlign: 'center' },
  c4: { flex: 1, textAlign: 'center' },
  c5: { flex: 2 },
  summary: { flexDirection: 'row', justifyContent: 'space-around', marginTop: 24, padding: 14, backgroundColor: '#F3F4F7', borderRadius: 6 },
  summaryItem: { alignItems: 'center' },
  big: { fontSize: 18, fontWeight: 'bold', color: '#00A0A8' },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, textAlign: 'center', color: '#78849E', fontSize: 9 },
});

export function ReportCardPDF({ data }: { data: ReportCard }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.school}>{data.tenant.name}</Text>
          <Text style={styles.sub}>Academic Report Card · Powered by Fenix SMS</Text>
        </View>

        <View style={styles.meta}>
          <View>
            <Text style={styles.label}>Student</Text>
            <Text>{data.student.name}</Text>
            <Text style={styles.label}>{data.student.studentNumber}</Text>
          </View>
          <View>
            <Text style={styles.label}>Term</Text>
            <Text>{data.term}</Text>
          </View>
        </View>

        <Text style={styles.title}>Subject results</Text>
        <View style={styles.tableHead}>
          <Text style={styles.c1}>Subject</Text>
          <Text style={styles.c2}>Score</Text>
          <Text style={styles.c3}>%</Text>
          <Text style={styles.c4}>Grade</Text>
          <Text style={styles.c5}>Remark</Text>
        </View>
        {data.subjects.map((s) => (
          <View key={s.code} style={styles.tableRow}>
            <Text style={styles.c1}>{s.subject}</Text>
            <Text style={styles.c2}>{s.score}/{s.maxScore}</Text>
            <Text style={styles.c3}>{s.percentage}%</Text>
            <Text style={styles.c4}>{s.letter}</Text>
            <Text style={styles.c5}>{s.remark ?? '—'}</Text>
          </View>
        ))}

        <View style={styles.summary}>
          <View style={styles.summaryItem}>
            <Text style={styles.big}>{data.summary.average}%</Text>
            <Text style={styles.label}>Average</Text>
          </View>
          <View style={styles.summaryItem}>
            <Text style={styles.big}>{data.summary.gpa}</Text>
            <Text style={styles.label}>GPA (4.0)</Text>
          </View>
          <View style={styles.summaryItem}>
            <Text style={styles.big}>{data.summary.totalSubjects}</Text>
            <Text style={styles.label}>Subjects</Text>
          </View>
        </View>

        <Text style={styles.footer}>Generated by Fenix SMS on {formatDate(new Date().toISOString())}.</Text>
      </Page>
    </Document>
  );
}
